version: '3.4'

services:
  auth.service:
    container_name: auth.service
    build: 
      context: .
      dockerfile: Services/Auth/Dockerfile
    restart: always
    depends_on:
      - mysql
      - rabbitmq

  account.service:
    container_name: account.service
    build: 
      context: .
      dockerfile: Services/Account/Account.API/Dockerfile
    restart: always
    depends_on:
      - mysql
      - rabbitmq
      - auth.service

  users.service:
    container_name: users.service
    build: 
      context: .
      dockerfile: Services/Users/Users.API/Dockerfile
    restart: always
    depends_on:
      - mysql
      - account.service
      - rabbitmq

  registration.app:
    container_name: registration.app
    build: 
      context: .
      dockerfile: Web/Registration/Dockerfile

  angularspa.app:
    container_name: angularspa.app
    build: 
      context: .
      dockerfile: Web/AngularSPA/Dockerfile

  account.apigw:
    container_name: account.apigw
    image: account.apigw
    build:
      context: ./ApiGateways/OcelotApiGw
    depends_on:
      - account.service

  users.apigw:
    container_name: users.apigw
    image: users.apigw
    build:
      context: ./ApiGateways/OcelotApiGw
    depends_on:
      - users.service

  rabbitmq:
    image: rabbitmq:3-management-alpine

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  flyway:
    image: flyway/flyway
    depends_on:
      - mysql

  nginx:
    image: nginx
    restart: always
    depends_on:
      - auth.service
      - account.apigw
      - registration.app
      - angularspa.app

  healthchecksui:
    image: xabarilcoding/healthchecksui
    depends_on:
        - auth.service
        - account.service
        - users.service
