version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
        - mysql

  flyway_test:
    image: flyway/flyway
    depends_on:
      - mysql